Controllers/agantController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc;
using MossadMVC.Models;
using System.Diagnostics;
using System.Net.Http;
using System.Text.Json;
using System.Text;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using static System.Net.Mime.MediaTypeNames;
using MossadMVC.View_Models;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MossadMVC.Controllers
{
    public class agantController : Controller
    {

        private readonly HttpClient _httpClient;

        public agantController()
        {
            _httpClient = new HttpClient();
        }


        public async Task<IActionResult> Page1()
        {
            ConnectPage1 page1 = new ConnectPage1();


            //get api count all agants
            var resultCountAllAgant = await _httpClient.GetStringAsync("http://localhost:5157/api/agants/count");
            //converting to the viewmodel
            page1.countAllAgants = JsonConvert.DeserializeObject<int>(resultCountAllAgant);


            //get api count active agants
            var resultActiveAgants = await _httpClient.GetStringAsync("http://localhost:5157/api/agants/Activecount");
            //converting to the viewmodel

            page1.countActiveAgants = JsonConvert.DeserializeObject<int>(resultActiveAgants);




            //get api count all targets
            var resultCountAllTargets = await _httpClient.GetStringAsync("http://localhost:5157/api/targets/count");
            //converting to the viewmodel

            page1.countAllTargets = JsonConvert.DeserializeObject<int>(resultCountAllTargets);


            //get api count all killed targets
            var resultCountKilled = await _httpClient.GetStringAsync("http://localhost:5157/api/targets/KilledCount");
            //converting to the viewmodel

            page1.countKilledTargets = JsonConvert.DeserializeObject<int>(resultCountKilled);



            //get api count all Missiles  
            var resultCountMissions = await _httpClient.GetStringAsync("http://localhost:5157/api/missions/count");
            //converting to the viewmodel

            page1.countAllMissions = JsonConvert.DeserializeObject<int>(resultCountMissions);


            //get api count active Missiles  
            var resultCountActiveMissions = await _httpClient.GetStringAsync("http://localhost:5157/api/missions/Activecount");
            //converting to the viewmodel

            page1.countActiveMissions = JsonConvert.DeserializeObject<int>(resultCountActiveMissions);

            //get api relative agant to targets 
            var resultRelativeAgantTargets = await _httpClient.GetStringAsync("http://localhost:5157/api/agants/relativeCount");
            //converting to the viewmodel

            page1.relativeAgantTargets =  resultRelativeAgantTargets;

            //get api relative agant to missions 
            var resultRelativeAgantMissions = await _httpClient.GetStringAsync("http://localhost:5157/api/agants/relativeAgantRoleCount");
            //converting to the viewmodel

            page1.relativeAgantMissions =   resultRelativeAgantMissions;







            return View(page1);
        }

        public async Task<IActionResult> Page2()
        {
 

             //get api all agants details
            var resultAllAgantDetails = await _httpClient.GetFromJsonAsync<AgantDetailsMVc[]>("http://localhost:5157/api/agants/allDetails");
            //converting to the viewmodel
            
            return View(resultAllAgantDetails);
        }

        public async Task<IActionResult> oneDetails(int id)
        {


             //get api all agants details
            var resultAgantDetails = await _httpClient.GetFromJsonAsync<AgantDetailsMVc[]>("http://localhost:5157/api/agants/allDetails");
            //converting to the viewmodel
 
            return View(resultAgantDetails);
        }

        public async Task<IActionResult> Page3()
        {
 
            //get api all agants details
            var resultAllAgantDetails = await _httpClient.GetFromJsonAsync<targetDetails[]>("http://localhost:5157/api/targets/allDetails");
            //converting to the viewmodel
 

             

            return View(resultAllAgantDetails);




             
        }

        public async Task<IActionResult> allMissions()
        {

            //get api all agants details
            var resultAllAgantDetails = await _httpClient.GetFromJsonAsync<MissionDetails[]>("http://localhost:5157/api/missions/allMissions");
            //converting to the viewmodel




            return View(resultAllAgantDetails);





        }

        public async Task<IActionResult> Active(int id)
        {
 
            //get api all agants details
            await _httpClient.PutAsJsonAsync($"http://localhost:5157/api/missions/{id}", "assigned");
            //converting to the viewmodel
            




            return RedirectToAction("allMissions");





        }

        public async Task<IActionResult> Update()
        {

            //get api all agants details
            await _httpClient.PutAsJsonAsync("http://localhost:5157/api/missions/update","");
            //converting to the viewmodel





            return RedirectToAction("allMissions");





        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MossadMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MossadMVC.styles.css" asp-append-version="true" />
    <meta http-equiv="refresh" content="5">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MossadMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="agant" asp-action="page1">Main Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="agant" asp-action="page2">Agants status</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="agant" asp-action="page3">Targets status</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="agant" asp-action="allMissions">Missions</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MossadMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>